In [2]:
import pandas as pd

data = pd.read_csv('train_ratings.csv')

data.head()

user  item        time test_a  test_b
0    11  4643  1230782529      a       1
1    11   170  1230782534      a       1
2    11   531  1230782539      a       1
3    11   616  1230782542      a       1
4    11  2140  1230782563      a       1

In [3]:
data = data.drop(columns=['Unnamed: 3'])
data

KeyError: "['Unnamed: 3'] not found in axis"

In [ ]:
data['test_a'] = "a"
data['test_b'] = "1"

In [ ]:
data

user  item        time test_a test_b
0      11  4643  1230782529      a      1
1      11   170  1230782534      a      1
2      11   531  1230782539      a      1
3      11   616  1230782542      a      1
4      11  2140  1230782563      a      1
..    ...   ...         ...    ...    ...
587    25  3686  1277962413      a      1
588    25  8910  1277962425      a      1
589    25  5225  1277962453      a      1
590    25  1126  1277962464      a      1
591    25  1721  1277962535      a      1

[592 rows x 5 columns]

In [ ]:
data.to_csv('train_ratings.csv', index=False)

In [1]:
import pandas as pd

data = pd.read_csv('train_ratings.csv')

In [2]:
data

user  item        time test_a  test_b
0      11  4643  1230782529      a       1
1      11   170  1230782534      a       1
2      11   531  1230782539      a       1
3      11   616  1230782542      a       1
4      11  2140  1230782563      a       1
..    ...   ...         ...    ...     ...
587    25  3686  1277962413      a       1
588    25  8910  1277962425      a       1
589    25  5225  1277962453      a       1
590    25  1126  1277962464      a       1
591    25  1721  1277962535      a       1

[592 rows x 5 columns]

In [6]:
data["test_a"].unique()

array(['a'], dtype=object)

In [11]:
data.iloc[[0, 2],0]

0    11
2    11
Name: user, dtype: int64

In [1]:
import torch

In [7]:
t = torch.arange(0, 2*3*4).view(2, 3, 4)
t

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [8]:
t.view(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])

In [2]:
a = torch.ShortTensor(range(10))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16)

In [3]:
import numpy as np
np.array(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [4]:
i = np.array([0, 2])
a[-(i+1)]

tensor([9, 7], dtype=torch.int16)

In [5]:
a[-i]

tensor([0, 8], dtype=torch.int16)

In [ ]:
temp = torch.ShortTensor(self.nodes.iloc[2:6])
node_query[target_idx + max_seq_len - seq_len] = temp[target_idx]
node_key[-seq_len:] = temp # 16bit signed integer
node_key[target_idx + max_seq_len - seq_len] = 0

In [9]:
temp = [i for i in range(1,11)]
query_idx = [1, 3 ,7]
default = 0

a = temp[: query_idx[0]]
for i in range(len(query_idx) - 1):
    a = a + [default] + temp[query_idx[i] : query_idx[i + 1]]
a = a + [default] + temp[query_idx[-1] :]

a

[1, 0, 2, 3, 0, 4, 5, 6, 7, 0, 8, 9, 10]